// <auto-generated />
using System;
using FarmaPrisa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmaPrisa.Migrations
{
    [DbContext(typeof(FarmaPrisaContext))]
    partial class FarmaPrisaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Branch", b =>
                {
                    b.Property<int>("IdBranch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdBranch"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DivisionesGeograficaId")
                        .HasColumnType("int(11)");

                    b.Property<int>("IdCompany")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdBranch");

                    b.HasIndex("DivisionesGeograficaId");

                    b.HasIndex("IdCompany");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Company", b =>
                {
                    b.Property<int>("IdCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCompany"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdCountry")
                        .HasColumnType("int(11)");

                    b.Property<int>("IdCurrency")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdCompany");

                    b.HasIndex("IdCountry");

                    b.HasIndex("IdCurrency");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Aseguradora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactoEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contacto_email");

                    b.Property<string>("ContactoTelefono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("contacto_telefono");

                    b.Property<bool?>("EstaActiva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("esta_activa")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Nombre" }, "nombre")
                        .IsUnique();

                    b.ToTable("aseguradoras", null, t =>
                        {
                            t.HasComment("Tabla para gestionar las aseguradoras, contendrá la lista de todas las compañías de seguros con las que la farmacia tiene convenio");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Brand", b =>
                {
                    b.Property<int>("IdBrand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdBrand"));

                    b.Property<int>("BranchIdBranch")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdBrand");

                    b.HasIndex("BranchIdBranch");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.CarritoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAgregado")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CarritoItems");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchIdBranch")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriaPadreId")
                        .HasColumnType("int(11)")
                        .HasColumnName("categoria_padre_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("BranchIdBranch");

                    b.HasIndex(new[] { "CategoriaPadreId" }, "categoria_padre_id");

                    b.ToTable("categorias", null, t =>
                        {
                            t.HasComment("Para organizar productos. El campo 'categoria_padre_id' nos permite crear subcategorías.");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Currency", b =>
                {
                    b.Property<int>("IdCurrency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCurrency"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Currencysymbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdCurrency");

                    b.ToTable("Currencys");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.DetailType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DetailType");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.DetallesPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesPedidos");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Direccione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CiudadId")
                        .HasColumnType("int(11)")
                        .HasColumnName("ciudad_id");

                    b.Property<string>("DireccionCompleta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccion_completa");

                    b.Property<bool?>("EsPredeterminada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_predeterminada")
                        .HasDefaultValueSql("'0'");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitud");

                    b.Property<string>("Referencia")
                        .HasColumnType("text")
                        .HasColumnName("referencia");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int(11)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CiudadId" }, "ciudad_id");

                    b.HasIndex(new[] { "UsuarioId" }, "usuario_id");

                    b.ToTable("direcciones", null, t =>
                        {
                            t.HasComment("Tabla para que los usuarios guarden múltiples direcciones de envío.");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.DivisionesGeografica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DivisionPadreId")
                        .HasColumnType("int(11)")
                        .HasColumnName("division_padre_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("TipoDivision")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo_division");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DivisionPadreId" }, "division_padre_id");

                    b.ToTable("divisiones_geograficas", null, t =>
                        {
                            t.HasComment("Tabla para las divisiones geográficas y referirnos a los continentes, países,  provincias, departamentos, ciudades, barrios, etc. según convenga");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.HorariosDomicilio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("HoraCierre")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.Property<int>("ZonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId");

                    b.ToTable("HorariosDomicilios");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.IngresoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadInicial")
                        .HasColumnType("int");

                    b.Property<int>("CantidadRestante")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("SucursalId");

                    b.ToTable("IngresosInventario");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.InventarioSucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("StockTotal")
                        .HasColumnType("int");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("SucursalId");

                    b.ToTable("InventariosSucursal");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.ItemsMedium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool?>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("esta_activo")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("media_url");

                    b.Property<int?>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("orden")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("SeccionId")
                        .HasColumnType("int(11)")
                        .HasColumnName("seccion_id");

                    b.Property<string>("TipoMedia")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('imagen','video')")
                        .HasColumnName("tipo_media")
                        .HasDefaultValueSql("'imagen'");

                    b.Property<string>("Titulo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("titulo");

                    b.Property<string>("UrlDestino")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("url_destino");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SeccionId" }, "seccion_id");

                    b.ToTable("items_media", null, t =>
                        {
                            t.HasComment("Para poder guardar los elementos de los archivos medias en las secciones");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Kardex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SaldoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("SaldoNuevo")
                        .HasColumnType("int");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<int>("TipoMovimientoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("TipoMovimientoId");

                    b.ToTable("Kardex");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.MetodosPagoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnoExpiracion")
                        .HasColumnType("int(11)")
                        .HasColumnName("ano_expiracion");

                    b.Property<bool?>("EsPredeterminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_predeterminado")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateTime?>("FechaAgregado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_agregado")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("GatewayToken")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("gateway_token");

                    b.Property<int?>("MesExpiracion")
                        .HasColumnType("int(11)")
                        .HasColumnName("mes_expiracion");

                    b.Property<string>("TipoTarjeta")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_tarjeta");

                    b.Property<string>("UltimosCuatroDigitos")
                        .HasMaxLength(4)
                        .HasColumnType("char(4)")
                        .HasColumnName("ultimos_cuatro_digitos")
                        .IsFixedLength();

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int(11)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "GatewayToken" }, "gateway_token")
                        .IsUnique();

                    b.HasIndex(new[] { "UsuarioId" }, "usuario_id")
                        .HasDatabaseName("usuario_id1");

                    b.ToTable("metodos_pago_usuario", null, t =>
                        {
                            t.HasComment("Tabla para la gestión de los métodos de pagos con");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.OpinionesProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaOpinion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductoIdProduct")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("producto_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoIdProduct");

                    b.HasIndex("UsuarioId");

                    b.ToTable("OpinionesProductos");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.OtpUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoOtp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codigo_otp");

                    b.Property<bool>("EstaUsado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("esta_usado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_expiracion");

                    b.Property<string>("TipoUso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_uso");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int(11)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("otps_usuario", (string)null);
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.PaginasInformativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AutorId")
                        .HasColumnType("int(11)")
                        .HasColumnName("autor_id");

                    b.Property<string>("ContenidoHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido_html");

                    b.Property<bool?>("EstaPublicada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("esta_publicada")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AutorId" }, "autor_id");

                    b.HasIndex(new[] { "Slug" }, "slug")
                        .IsUnique();

                    b.ToTable("paginas_informativas", null, t =>
                        {
                            t.HasComment("Páginas con información estática, con esta tabla, el administrador podrá crear y editar fácilmente el contenido de estas páginas desde el panel de control.");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoEnvio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("DireccionId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaPedido")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("MontoDescuento")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MontoImpuesto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("RecetaId")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("SucursalRecogidaId")
                        .HasColumnType("int");

                    b.Property<string>("TipoEntrega")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("DireccionId");

                    b.HasIndex("RecetaId");

                    b.HasIndex("SucursalRecogidaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.PlantillaProductos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlantillaProductos");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdProduct");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProduct"));

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int(11)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int(11)");

                    b.HasKey("IdProduct");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.ProductDetail", b =>
                {
                    b.Property<int>("IdProductDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProductDetail"));

                    b.Property<string>("DetailText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DetailTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoDetalleId")
                        .HasColumnType("int");

                    b.HasKey("IdProductDetail");

                    b.HasIndex("DetailTypeId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TipoDetalleId");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.ProductoImagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_principal");

                    b.Property<int>("Orden")
                        .HasColumnType("int(11)")
                        .HasColumnName("orden");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int(11)")
                        .HasColumnName("producto_id");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("url_imagen");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("ProductoId");

                    b.ToTable("producto_imagenes", (string)null);
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.ProductoSintoma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("SintomaId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("SintomaId");

                    b.ToTable("ProductoSintomas");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.PromocionCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int(11)")
                        .HasColumnName("categoria_id");

                    b.Property<int>("PromocionId")
                        .HasColumnType("int(11)")
                        .HasColumnName("promocion_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CategoriaId" }, "categoria_id");

                    b.HasIndex(new[] { "PromocionId" }, "promocion_id");

                    b.ToTable("promocion_categorias", null, t =>
                        {
                            t.HasComment("Tabla para aplicar una promoción a categorías enteras");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.PromocionProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("PromocionId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("PromocionId");

                    b.ToTable("PromocionProductos");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Promocione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoCupon")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo_cupon");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool?>("EstaActiva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("esta_activa")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("TipoDescuento")
                        .IsRequired()
                        .HasColumnType("enum('porcentaje','fijo')")
                        .HasColumnName("tipo_descuento");

                    b.Property<decimal>("ValorDescuento")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_descuento");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CodigoCupon" }, "codigo_cupon")
                        .IsUnique();

                    b.ToTable("promociones", null, t =>
                        {
                            t.HasComment("Tabla principal para definir cada promoción");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Proveedore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailContacto")
                        .HasColumnType("longtext");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("esta_activo");

                    b.Property<string>("IdentificacionFiscal")
                        .HasColumnType("longtext");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreContacto")
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonoContacto")
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Nombre" }, "nombre")
                        .IsUnique()
                        .HasDatabaseName("nombre1");

                    b.ToTable("proveedores", null, t =>
                        {
                            t.HasComment("Tabla para los proveedores o laboratorios.");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.RecetasMedica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComentariosAdmin")
                        .HasColumnType("text")
                        .HasColumnName("comentarios_admin");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pendiente','aprobada','rechazada','usada')")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'pendiente'");

                    b.Property<DateTime?>("FechaCarga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_carga")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("imagen_url");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int(11)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UsuarioId" }, "usuario_id")
                        .HasDatabaseName("usuario_id2");

                    b.ToTable("recetas_medicas", null, t =>
                        {
                            t.HasComment("Tabla para que los usuarios suban sus recetas");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Nombre" }, "nombre")
                        .IsUnique()
                        .HasDatabaseName("nombre2");

                    b.ToTable("roles", null, t =>
                        {
                            t.HasComment("Tabla para los roles");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.SeccionesMedium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("IdentificadorUnico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("identificador_unico");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdentificadorUnico" }, "identificador_unico")
                        .IsUnique();

                    b.ToTable("secciones_media", null, t =>
                        {
                            t.HasComment("Tabla para definir las ubicaciones o secciones de media en el sitio");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Sintoma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Nombre" }, "nombre")
                        .IsUnique()
                        .HasDatabaseName("nombre3");

                    b.ToTable("sintomas", null, t =>
                        {
                            t.HasComment("Tabla para almacenar todos los posibles síntomas.");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.TasasImpuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("PaisId")
                        .HasColumnType("int(11)")
                        .HasColumnName("pais_id");

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PaisId" }, "pais_id");

                    b.ToTable("tasas_impuestos", null, t =>
                        {
                            t.HasComment("Tabla para la gestión de los impuestos según el país");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.TipoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("esta_activo");

                    b.Property<string>("IdentificadorUnico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("identificador_unico");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("IdentificadorUnico")
                        .IsUnique();

                    b.ToTable("tipo_detalles", (string)null);
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.TipoMovimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EsAjuste")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsIngreso")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposMovimiento");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Transaccione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("enum('exitoso','fallido')")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_transaccion")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("IdTransaccionPasarela")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id_transaccion_pasarela");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto");

                    b.Property<string>("PasarelaPago")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pasarela_pago");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int(11)")
                        .HasColumnName("pedido_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PedidoId" }, "pedido_id");

                    b.ToTable("transacciones", null, t =>
                        {
                            t.HasComment("Tabla para guardar un registro del pago");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool?>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("esta_activo")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateTime?>("FechaActualizacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("current_timestamp()");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaActualizacion"));

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre_completo");

                    b.Property<int>("PaisId")
                        .HasColumnType("int(11)")
                        .HasColumnName("pais_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int(11)")
                        .HasColumnName("proveedor_id");

                    b.Property<int>("PuntosFidelidad")
                        .HasColumnType("int(11)")
                        .HasColumnName("puntos_fidelidad");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "PaisId" }, "pais_id")
                        .HasDatabaseName("pais_id1");

                    b.HasIndex(new[] { "ProveedorId" }, "proveedor_id");

                    b.HasIndex(new[] { "Telefono" }, "telefono")
                        .IsUnique();

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasComment("Tabla para los usuarios.");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.UsuarioAseguradora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AseguradoraId")
                        .HasColumnType("int(11)")
                        .HasColumnName("aseguradora_id");

                    b.Property<bool?>("EstaVerificada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("esta_verificada")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateTime?>("FechaAgregado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_agregado")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("NumeroPoliza")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("numero_poliza");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int(11)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AseguradoraId" }, "aseguradora_id");

                    b.HasIndex(new[] { "UsuarioId" }, "usuario_id")
                        .HasDatabaseName("usuario_id3");

                    b.ToTable("usuario_aseguradoras", null, t =>
                        {
                            t.HasComment("Tabla para Vincular Usuarios con Aseguradoras  conecta a cada usuario con su respectiva aseguradora y guarda su número de póliza. Esto permite que un usuario pueda tener pólizas con una o más aseguradoras.");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.UsuarioRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RolId")
                        .HasColumnType("int(11)")
                        .HasColumnName("rol_id");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int(11)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RolId" }, "rol_id");

                    b.HasIndex(new[] { "UsuarioId", "RolId" }, "uq_usuario_rol")
                        .IsUnique();

                    b.ToTable("usuario_roles", null, t =>
                        {
                            t.HasComment("Tabla para la relación de los Usuarios con los Roles");
                        });
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.ZonasDomicilio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoEnvio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<bool?>("EstaActiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.ToTable("ZonasDomicilios");
                });

            modelBuilder.Entity("Branch", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.DivisionesGeografica", null)
                        .WithMany("Sucursales")
                        .HasForeignKey("DivisionesGeograficaId");

                    b.HasOne("Company", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Company", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.DivisionesGeografica", "Country")
                        .WithMany()
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaPrisa.Models.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("IdCurrency")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Brand", b =>
                {
                    b.HasOne("Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchIdBranch")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.CarritoItem", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Usuario", "Usuario")
                        .WithMany("CarritoItems")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Categoria", b =>
                {
                    b.HasOne("Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchIdBranch")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaPrisa.Models.Entities.Categoria", "CategoriaPadre")
                        .WithMany("InverseCategoriaPadre")
                        .HasForeignKey("CategoriaPadreId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("categorias_ibfk_1");

                    b.Navigation("Branch");

                    b.Navigation("CategoriaPadre");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.DetallesPedido", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Pedido", "Pedido")
                        .WithMany("DetallesPedidos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaPrisa.Models.Entities.Product", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Direccione", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.DivisionesGeografica", "Ciudad")
                        .WithMany("Direcciones")
                        .HasForeignKey("CiudadId")
                        .IsRequired()
                        .HasConstraintName("direcciones_ibfk_2");

                    b.HasOne("FarmaPrisa.Models.Entities.Usuario", "Usuario")
                        .WithMany("Direcciones")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("direcciones_ibfk_1");

                    b.Navigation("Ciudad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.DivisionesGeografica", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.DivisionesGeografica", "DivisionPadre")
                        .WithMany("InverseDivisionPadre")
                        .HasForeignKey("DivisionPadreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("divisiones_geograficas_ibfk_1");

                    b.Navigation("DivisionPadre");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.HorariosDomicilio", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.ZonasDomicilio", "Zona")
                        .WithMany("HorariosDomicilios")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.IngresoInventario", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Product", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Branch", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.InventarioSucursal", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Product", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Branch", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.ItemsMedium", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.SeccionesMedium", "Seccion")
                        .WithMany("ItemsMedia")
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("items_media_ibfk_1");

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Kardex", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Product", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Branch", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaPrisa.Models.Entities.TipoMovimiento", "TipoMovimiento")
                        .WithMany()
                        .HasForeignKey("TipoMovimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Sucursal");

                    b.Navigation("TipoMovimiento");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.MetodosPagoUsuario", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Usuario", "Usuario")
                        .WithMany("MetodosPagoUsuarios")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("metodos_pago_usuario_ibfk_1");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.OpinionesProducto", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Product", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoIdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaPrisa.Models.Entities.Usuario", "Usuario")
                        .WithMany("OpinionesProductos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.OtpUsuario", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Usuario", "Usuario")
                        .WithMany("OtpsUsuario")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("otps_usuario_ibfk_1");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.PaginasInformativa", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Usuario", "Autor")
                        .WithMany("PaginasInformativas")
                        .HasForeignKey("AutorId")
                        .HasConstraintName("paginas_informativas_ibfk_1");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Pedido", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Direccione", "Direccion")
                        .WithMany("Pedidos")
                        .HasForeignKey("DireccionId");

                    b.HasOne("FarmaPrisa.Models.Entities.RecetasMedica", "Receta")
                        .WithMany("Pedidos")
                        .HasForeignKey("RecetaId");

                    b.HasOne("Branch", "SucursalRecogida")
                        .WithMany()
                        .HasForeignKey("SucursalRecogidaId");

                    b.HasOne("FarmaPrisa.Models.Entities.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Direccion");

                    b.Navigation("Receta");

                    b.Navigation("SucursalRecogida");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Product", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaPrisa.Models.Entities.Categoria", "Category")
                        .WithMany("Productos")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaPrisa.Models.Entities.Proveedore", "Supplier")
                        .WithMany("Productos")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.ProductDetail", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.DetailType", "DetailType")
                        .WithMany("ProductDetails")
                        .HasForeignKey("DetailTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaPrisa.Models.Entities.Product", "Product")
                        .WithMany("Details")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaPrisa.Models.Entities.TipoDetalle", null)
                        .WithMany("ProductoDetalles")
                        .HasForeignKey("TipoDetalleId");

                    b.Navigation("DetailType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.ProductoImagen", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Product", "Product")
                        .WithMany("Imagenes")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("producto_imagenes_ibfk_1");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.ProductoSintoma", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Product", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");

                    b.HasOne("FarmaPrisa.Models.Entities.Sintoma", "Sintoma")
                        .WithMany("ProductoSintomas")
                        .HasForeignKey("SintomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Sintoma");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.PromocionCategoria", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Categoria", "Categoria")
                        .WithMany("PromocionCategoria")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("promocion_categorias_ibfk_2");

                    b.HasOne("FarmaPrisa.Models.Entities.Promocione", "Promocion")
                        .WithMany("PromocionCategoria")
                        .HasForeignKey("PromocionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("promocion_categorias_ibfk_1");

                    b.Navigation("Categoria");

                    b.Navigation("Promocion");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.PromocionProducto", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Product", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");

                    b.HasOne("FarmaPrisa.Models.Entities.Promocione", "Promocion")
                        .WithMany("PromocionProductos")
                        .HasForeignKey("PromocionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Promocion");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.RecetasMedica", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Usuario", "Usuario")
                        .WithMany("RecetasMedicas")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("recetas_medicas_ibfk_1");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.TasasImpuesto", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.DivisionesGeografica", "Pais")
                        .WithMany("TasasImpuestos")
                        .HasForeignKey("PaisId")
                        .IsRequired()
                        .HasConstraintName("tasas_impuestos_ibfk_1");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Transaccione", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Pedido", "Pedido")
                        .WithMany("Transacciones")
                        .HasForeignKey("PedidoId")
                        .IsRequired()
                        .HasConstraintName("transacciones_ibfk_1");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Usuario", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.DivisionesGeografica", "Pais")
                        .WithMany("Usuarios")
                        .HasForeignKey("PaisId")
                        .IsRequired()
                        .HasConstraintName("usuarios_ibfk_2");

                    b.HasOne("FarmaPrisa.Models.Entities.Proveedore", "Proveedor")
                        .WithMany("Usuarios")
                        .HasForeignKey("ProveedorId")
                        .HasConstraintName("usuarios_ibfk_1");

                    b.Navigation("Pais");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.UsuarioAseguradora", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Aseguradora", "Aseguradora")
                        .WithMany("UsuarioAseguradoras")
                        .HasForeignKey("AseguradoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("usuario_aseguradoras_ibfk_2");

                    b.HasOne("FarmaPrisa.Models.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioAseguradoras")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("usuario_aseguradoras_ibfk_1");

                    b.Navigation("Aseguradora");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.UsuarioRole", b =>
                {
                    b.HasOne("FarmaPrisa.Models.Entities.Role", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("usuario_roles_ibfk_2");

                    b.HasOne("FarmaPrisa.Models.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("usuario_roles_ibfk_1");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.ZonasDomicilio", b =>
                {
                    b.HasOne("Branch", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Company", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Aseguradora", b =>
                {
                    b.Navigation("UsuarioAseguradoras");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Categoria", b =>
                {
                    b.Navigation("InverseCategoriaPadre");

                    b.Navigation("Productos");

                    b.Navigation("PromocionCategoria");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.DetailType", b =>
                {
                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Direccione", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.DivisionesGeografica", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("InverseDivisionPadre");

                    b.Navigation("Sucursales");

                    b.Navigation("TasasImpuestos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Pedido", b =>
                {
                    b.Navigation("DetallesPedidos");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Product", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Imagenes");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Promocione", b =>
                {
                    b.Navigation("PromocionCategoria");

                    b.Navigation("PromocionProductos");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Proveedore", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.RecetasMedica", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Role", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.SeccionesMedium", b =>
                {
                    b.Navigation("ItemsMedia");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Sintoma", b =>
                {
                    b.Navigation("ProductoSintomas");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.TipoDetalle", b =>
                {
                    b.Navigation("ProductoDetalles");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.Usuario", b =>
                {
                    b.Navigation("CarritoItems");

                    b.Navigation("Direcciones");

                    b.Navigation("MetodosPagoUsuarios");

                    b.Navigation("OpinionesProductos");

                    b.Navigation("OtpsUsuario");

                    b.Navigation("PaginasInformativas");

                    b.Navigation("Pedidos");

                    b.Navigation("RecetasMedicas");

                    b.Navigation("UsuarioAseguradoras");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("FarmaPrisa.Models.Entities.ZonasDomicilio", b =>
                {
                    b.Navigation("HorariosDomicilios");
                });
#pragma warning restore 612, 618
        }
    }
}
